name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0 
    - name: Docker login 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image #Paso para contruit la imagen
      run: docker build --tag victor281201/docker-graphql:0.0.2 . #Construimos la imagen (Por los momentos ponemos el versionamiento asi)
    - name: Push the Docker image #Paso para subir la imagen a Docker Hub
      run: |
        docker push victor281201/docker-graphql:0.0.2 #Subimos la imagen a Docker Hub

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
